### ISSUE TITLE
Get list of all notifications

### ISSUE THREAD

**Issue by mighty-phoenix** [Sur-un-nuage/strapi-plugin-expo-notifications#1]
Is it possible to get all notifications in a list using an API?
Need a way to get all the notifications.
Thanks! @philohelp

**Comment by philohelp** [comment]
Yes there's a route for that. But you'll have to tweak the auth.
https://github.com/Sur-un-nuage/strapi-plugin-expo-notifications/blob/main/server/routes/index.js

You could do for example:
[STRAPI URL]/expo-notifications/findFrom/?page=1&pageSize=20

**Comment by mighty-phoenix** [comment]
@philohelp First, I was getting:
```
{
    "data": null,
    "error": {
        "status": 401,
        "name": "UnauthorizedError",
        "message": "Missing or invalid credentials",
        "details": {}
    }
}
```

Now after uncommenting ` auth: false `, in the [file you shared above](https://github.com/Sur-un-nuage/strapi-plugin-expo-notifications/blob/main/server/routes/index.js), I'm getting:
```
{
    "data": null,
    "error": {
        "status": 403,
        "name": "PolicyError",
        "message": "Policy Failed",
        "details": {}
    }
}
```

Please help me out here. I shall be very grateful.
Thanks!

All I want is a working API to get the list of all the notifications(in a paginated/non-paginated way, doesn't matter).
Kindly guide me.
Thanks again! @philohelp

**Comment by mighty-phoenix** [comment]
@philohelp  I was able to make it work.
Thanks for the assistance. :)
