### ISSUE TITLE
Read receipt for notifications for a given user

### ISSUE THREAD

**Issue by mighty-phoenix** [Sur-un-nuage/strapi-plugin-expo-notifications#2]
Hey @philohelp @Sur-un-nuage
I want to check if a given user has read a notification or not, using a field in an API response.
I also want a POST API to mark a notification as read for a given user.
I also want a POT API to mark all notifications as read for a given user.
How can I accomplish the same?
Quick response would be highly appreciated.
Thank you.

**Comment by philohelp** [comment]
1- I think it's not possible to determine whether the user has simply viewed the notification in the notification center, the notification center being managed by the device's operating system. 
2- But it is possible - and fairly easy - to capture the read event once the app is opened. The listeners and handlers are described in the expo docs: https://docs.expo.dev/versions/latest/sdk/notifications/ I have this done with Amplitude in one of my project, but you could as well send something back to any Strapi endpoint. You have the notifications endpoint and model at your disposal, it could be a start.
3- The possibility to add JSON data to a notification is on the roadmap of the plugin and it would be a rather simple & natural addition. Unfortunately I won't be able to work on it before weeks, so PR are welcome.
